### ISSUE TITLE
As a user, I can view a display of movies when I load the homepage.

### ISSUE THREAD

**Issue by kelleyej** [dkwon1223/rancid-tomatillos#1]
As a user, I can view a display of movies when I load the web page. 

What steps need to be taken to accomplish this task?

- [x] The user must navigate to the web page. 

When the task is executed, what happens? What does the user see?

- [x] The user will view a UI on page load consisting of a display of several movies, which may include the movie title, movie poster image, average rating, and release date. 

Requirements for accomplished/completed status

- [x] Appropriate DOM rendering on page load.

**Comment by kelleyej** [comment]
As a user, I can view a display of movies when I load the homepage. 

What steps need to be taken to accomplish this task?

- [ ] The user must navigate to the web page. 

When the task is executed, what happens? What does the user see?

- [ ] The user will view a UI on page load consisting of a display of several movies, which include the movie title, movie poster image, average rating, and release date. 

Requirements for accomplished/completed status

- [ ] Load the web page.

**Comment by dkwon1223** [comment]
Seems like this user story is almost done! After reading your second checkbox, I think it would be pretty cool to show some more details with average rating and release date which can come with our CSS enhancements coming soon.

**Comment by dkwon1223** [comment]
I believe with our recent work and PRs (display movies, movie details, and styling enhancements) we have completed this ticket
